name: Read the Docs Placeholder

on:
  workflow_dispatch:

jobs:
  docs-note:
    runs-on: ubuntu-latest
    steps:
      - name: Read the Docs handles docs builds
        run: echo "Docs for krnel-graph are built by Read the Docs, not GitHub Actions. Manage the pipeline at https://readthedocs.org/dashboard/krnel-graph/."
